const base = `${process.env.PUBLIC_URL}/images`;
// const base = "/images";

const Resources = {
  images: {
    Common: {
      backArrow: `${base}/Common/backArrow.svg`,
      bookNow: `${base}/Common/BookNow.jpg`,
      bookNowBanner: `${base}/Common/BookNowBanner.jpg`,
      bookNowBannerMobile: `${base}/Common/BookNowBannerMob.jpg`,
      BookNowTabletView: `${base}/Common/BookNowTabletView.jpg`,
      bookNowCard: `${base}/Common/bookNowCard.webp`,
      blackNoise: `${base}/Common/black-noise.png`,
      cardBg1: `${base}/Common/cards-background.svg`,
      cardBg2: `${base}/Common/cards-bg-2.png`,
      bookNowCard2: `${base}/Common/book-now.png`,
      searchIcon: `${base}/Common/searchIcon.svg`,
      filterIcon: `${base}/Common/Filter.svg`,
      dropdownIcon: `${base}/Common/DropdownIcon.svg`,
      dermat: `${base}/Common/dermat.png`,
      emptyCart: `${base}/Common/empty-cart.png`,
      removeItem: `${base}/Common/remove-from-cart.png`,
      personalisedPlanning: `${base}/Common/personalized-planning.png`,
      serviceAtHome: `${base}/Common/service-at-home.svg`,
      personalDr: `${base}/Common/personalised-doctor.svg`,
    },
    NavBar: {
      notificationIcon: `${base}/NavBar/notification.svg`,
      profileIcon: `${base}/NavBar/profileIcon.svg`,
      userProfile: `${base}/NavBar/userProfile.svg`,
      logout: `${base}/NavBar/logout.svg`,
      marksAsRead: `${base}/NavBar/markAllAsRead.svg`,
      branding: `${base}/NavBar/branding.jpeg`,
      logo1: `${base}/NavBar/Logo1.png`,
      logo2: `${base}/NavBar/Logo1.svg`,
    },
    PageNotFound: {
      Crack1: `${base}/PageNotFound/Crack1.svg`,
      Crack2: `${base}/PageNotFound/Crack2.svg`,
      NotFound: `${base}/PageNotFound/NotFound.svg`,
    },
    Warning: {
      error: `${base}/Warning/Error.svg`,
      warning: `${base}/Warning/Warning.svg`,
      information: `${base}/Warning/Information.svg`,
    },
    Carousel: {
      headerOne: `${base}/Carousel/carousel-img-1.jpeg`,
    },
    Services: {
      mediFacial: `${base}/Services/medi-facial.jpeg`,
      mediFacialPackage: `${base}/Services/medi-facial-package.jpg`,
      whyUs: `${base}/Services/why-us.jpg`,
      feedback: `${base}/Services/feedback.jpg`,
      LaserHairRemoval: {
        laserHairSelectedPart: `${base}/Services/LaserHairRemoval/Women/img7.webp`,
        hairRemovalBookNow: `${base}/Services/LaserHairRemoval/HairRemovalBookNow.jpg`,
        laserHairRemovalCard: `${base}/Services/LaserHairRemoval/laser-hair-removal.webp`,
        faceAndNeck: `${base}/Services/LaserHairRemoval/faceAndNeck.jpg`,
        bikiniAndButtocks: `${base}/Services/LaserHairRemoval/bikiniAndButtocks.jpg`,
        underarms: `${base}/Services/LaserHairRemoval/Underarms.webp`,
        fullBodyWomenLHR: `${base}/Services/LaserHairRemoval/fullBodyWomenLHR.jpg`,
        fullBodyMenLHR: `${base}/Services/LaserHairRemoval/fullBodyMenLHR.jpg`,
        chestAndBack: `${base}/Services/LaserHairRemoval/chest-back.webp`,
        home: `${base}/Services/LaserHairRemoval/home.png`,
        machine: `${base}/Services/LaserHairRemoval/machine.webp`,
        back: `${base}/Services/LaserHairRemoval/back.jpg`,
        bikini: `${base}/Services/LaserHairRemoval/bikini.jpg`,
        chest: `${base}/Services/LaserHairRemoval/chest.jpg`,
        facial: `${base}/Services/LaserHairRemoval/facial.jpg`,
        fullLegs: `${base}/Services/LaserHairRemoval/full-legs.jpg`,
        underarmsIcon: `${base}/Services/LaserHairRemoval/underarms.jpg`,
        Men: {
          headerMen: `${base}/Services/LaserHairRemoval/Men/header.jpg`,
          headerMenMobile: `${base}/Services/LaserHairRemoval/Men/headerMobile.jpg`,
          imageOne: `${base}/Services/LaserHairRemoval/Men/img1.webp`,
          imageTwo: `${base}/Services/LaserHairRemoval/Men/img2.webp`,
          imageThree: `${base}/Services/LaserHairRemoval/Men/img3.webp`,
          imageFour: `${base}/Services/LaserHairRemoval/Men/img4.webp`,
          image5: `${base}/Services/LaserHairRemoval/Men/LHR-Men-img2.webp`,
        },
        Women: {
          headerWomen: `${base}/Services/LaserHairRemoval/Women/header.jpg`,
          imageOne: `${base}/Services/LaserHairRemoval/Women/img1.webp`,
          imageTwo: `${base}/Services/LaserHairRemoval/Women/img2.webp`,
          imageThree: `${base}/Services/LaserHairRemoval/Women/img3.webp`,
          imageFour: `${base}/Services/LaserHairRemoval/Women/img4.webp`,
          imageFive: `${base}/Services/LaserHairRemoval/Women/img5.webp`,
          imageSix: `${base}/Services/LaserHairRemoval/Women/img6.webp`,
          imageSeven: `${base}/Services/LaserHairRemoval/Women/img7.webp`,
        },
      },
      OxyGeneo: {
        header: `${base}/Services/Oxygeneo/header.jpg`,
        oxygeneoCard: `${base}/Services/Oxygeneo/oxygeneoCard.jpg`,
        img1: `${base}/Services/Oxygeneo/img1.jpg`,
        img2: `${base}/Services/Oxygeneo/img2.jpg`,
        img4: `${base}/Services/Oxygeneo/img4.png`,
        img5: `${base}/Services/Oxygeneo/img5.png`,
        img6: `${base}/Services/Oxygeneo/img6.jpg`,
        exfoliate: `${base}/Services/Oxygeneo/exfoliate.png`,
        infuse: `${base}/Services/Oxygeneo/infuse.png`,
        oxygenate: `${base}/Services/Oxygeneo/oxygenate.png`,
      },
      OxyHydra: {
        oxyHydraCard: `${base}/Services/OxyHydra/oxyHydra.jpg`,
        header2: `${base}/Services/OxyHydra/header2.jpg`,
        header3: `${base}/Services/OxyHydra/header3.jpg`,
        header: `${base}/Services/OxyHydra/header.jpg`,
        img1: `${base}/Services/OxyHydra/img1.webp`,
        img2: `${base}/Services/OxyHydra/img2.jpg`,
        img3: `${base}/Services/OxyHydra/img3.jpg`,
        img4: `${base}/Services/OxyHydra/img4.jpg`,
        oxyPackage: `${base}/Services/OxyHydra/oxy-package.jpg`,
      },
      SkinTightening: {
        skinTighteningCard: `${base}/Services/SkinTightening/skinTighteningCard.jpg`,
        header: `${base}/Services/SkinTightening/header.jpg`,
        img1: `${base}/Services/SkinTightening/img1.jpg`,
        img2: `${base}/Services/SkinTightening/img2.jpg`,
        img3: `${base}/Services/SkinTightening/img3.jpg`,
        img4: `${base}/Services/SkinTightening/img4.png`,
        img5: `${base}/Services/SkinTightening/img5.jpg`,
        img6: `${base}/Services/SkinTightening/img6.jpg`,
        img7: `${base}/Services/SkinTightening/img7.jpg`,
        skinPackage: `${base}/Services/SkinTightening/skin-package.jpg`,
      },
      Dermafrac: {
        dermafracCard: `${base}/Services/Dermafrac/dermafracCard.jpg`,
        header: `${base}/Services/Dermafrac/header.jpg`,
        imageOne: `${base}/Services/Dermafrac/img1.webp`,
        imageTwo: `${base}/Services/Dermafrac/img2.webp`,
        imageThree: `${base}/Services/Dermafrac/img3.webp`,
        imageFour: `${base}/Services/Dermafrac/img4.webp`,
        image5: `${base}/Services/Dermafrac/img5.webp`,
        img6: `${base}/Services/Dermafrac/img6.jpg`,
        dermaPackage: `${base}/Services/Dermafrac/derma-package.jpg`,
      },
    },
    Login: {
      loginBg: `${base}/Login/login-bg.webp`,
      signupBg: `${base}/Login/signup-bg.jpg`,
      signupBgMobile: `${base}/Login/signupMobile.jpg`,
    },
    ContactUs: {
      contactUs: `${base}/ContactUs/contactUs.jpg`,
    },
    Products: {
      img1: `${base}/Products/img1.jpg`,
      img2: `${base}/Products/img2.jpg`,
      img3: `${base}/Products/img3.jpg`,
      img4: `${base}/Products/img4.jpg`,
      img5: `${base}/Products/img5.jpg`,
      img6: `${base}/Products/img6.jpg`,
    }
  },
};

export default Resources;
