const base = `${process.env.PUBLIC_URL}/images`;
// const base = "http://localhost:5000/images";

const Resources = {
  images: {
    Common: {
      backArrow: `${base}/Common/backArrow.svg`,
      blackNoise: `${base}/Common/black-noise.png`,
      cardBg2: `${base}/Common/cards-bg-2.png`,
      searchIcon: `${base}/Common/SearchIcon.svg`,
      filterIcon: `${base}/Common/Filter.svg`,
      dropdownIcon: `${base}/Common/DropdownIcon.svg`,
      emptyCart: `${base}/Common/empty-cart.png`,
      removeItem: `${base}/Common/remove-from-cart.png`,
      homeHeader: `${base}/Common/homeHeader.jpg`,
      homeHeaderMobile: `${base}/Common/home-header-mobile.jpg`,
      dotsBg: `${base}/Common/dotsbg.svg`,
      newLogoBlack: `${base}/Common/new_log_black.png`,
      newLogoWhite: `${base}/Common/new_log_white.png`,
      offerBannerMobile: `${base}/Common/off_banner_mobile.jpg`,
      offerBannerLaptop: `${base}/Common/off_banner_laptop.jpg`,
      googlePlayButton: `${base}/Common/google-play.png`,
      fiftyPercentAfterServiceBanner: `${base}/Common/50-off-banner.jpg`,
      fiftyPercentAfterServiceBannerMobile: `${base}/Common/50-off-banner-mobile.jpg`,
      Warning: `${base}/Common/Warning.svg`,
      logoNavbar: `${base}/Common/logo_coal.png`,
      googleGLogo: `${base}/Common/google_g_logo.webp`,
      ourFeature: `${base}/Common/features.jpg`,
    },
    Home: {
      dermfracMobile: `${base}/Home/dermfrac-mobile.png`,
      dermfrac: `${base}/Home/dermfrac.jpg`,
      dermafracHeader: `${base}/Home/dermafracHeader.png`,
      dermafracPackage: `${base}/Home/dermafracPackage.png`,
      lhrMenMobile: `${base}/Home/lhr-men-mobile.png`,
      lhrMen: `${base}/Home/lhr-men.jpg`,
      lhrMenHeader: `${base}/Home/lhrMenHeader.png`,
      lhrWomenMobile: `${base}/Home/lhr-women-mobile.png`,
      lhrWomen: `${base}/Home/lhr-women.jpg`,
      lhrWomenHeader: `${base}/Home/lhrWomenHeader.jpg`,
      oxygeneoMobile: `${base}/Home/oxygeneo-mobile.png`,
      oxygeneo: `${base}/Home/oxygeneo.jpg`,
      oxygeneoHeader: `${base}/Home/oxygeneoHeader.png`,
      oxygeneoPackage: `${base}/Home/oxygeneoPackage.png`,
      oxyhydraMoble: `${base}/Home/oxyhydra-mobile.png`,
      oxyhydra: `${base}/Home/oxyhydra.jpg`,
      oxyhydraHeader: `${base}/Home/oxyhydraHeader.png`,
      oxyhydraPackage: `${base}/Home/oxyhydraPackage.jpg`,
      skinTighteningMobile: `${base}/Home/skin-tightening-mobile.png`,
      skinTightening: `${base}/Home/skin-tightening.jpg`,
      skinTighteningHeader: `${base}/Home/skinTighteningHeader.png`,
      skinTighteningPackage: {
        STAbdomenPackage: `${base}/Home/STAbdomenPackage.png`,
        STAnklesFeetKneePackage: `${base}/Home/STAnklesFeetKneePackage.png`,
        STArmsPackage: `${base}/Home/STArmsPackage.png`,
        STChinPackage: `${base}/Home/STChinPackage.png`,
        STDColletPackage: `${base}/Home/STDColletPackage.png`,
        STFacePackage: `${base}/Home/STFacePackage.png`,
        STFullFace: `${base}/Home/STFullFace.png`,
        STInnerThighPackage: `${base}/Home/STInnerThighPackage.png`,
        STOuterThighs: `${base}/Home/STOuterThighs.png`,
      },
      lhr: {
        armsPackage: `${base}/Home/armsPackage.png`,
        fullBodyFemalePackage: `${base}/Home/full-body-female-package.png`,
        fullBodyMalePackage: `${base}/Home/full-body-male-package.png`,
        facePackage: `${base}/Home/facePackage.png`,
        fullLegsPackage: `${base}/Home/fullLegsPackage.png`,
        halfLegsPackage: `${base}/Home/halfLegsPackage.png`,
        backPackage: `${base}/Home/fullBackPackage.png`,
        chestPackage: `${base}/Home/chestPackage.png`,
        chestMenPackage: `${base}/Home/chestMenPackage.png`,
        bikiniPackage: `${base}/Home/bikiniPackage.png`,
        underarmsPackage: `${base}/Home/underarmsPackage.png`,
      },
      customPackages: {
        customPackageImg1: `${base}/Home/customPackageImg1.jpeg`,
        customPackageImg2: `${base}/Home/customPackageImg2.jpeg`,
        customPackageImg3: `${base}/Home/customPackageImg3.jpg`,
        customPackageImg4: `${base}/Home/customPackageImg4.jpg`,
        customPackageImg5: `${base}/Home/customPackageImg5.jpg`,
        customPackageImg6: `${base}/Home/customPackageImg6.jpg`,
      },
      serviceCards: {
        dermafrac: `${base}/Home/serviceCards/dermafrac.jpg`,
        lhrMen: `${base}/Home/serviceCards/lhr_men.jpg`,
        lhrWomen: `${base}/Home/serviceCards/lhr_women.jpg`,
        oxygeneo: `${base}/Home/serviceCards/oxygeneo.jpg`,
      },
    },
    NavBar: {
      notificationIcon: `${base}/NavBar/notification.svg`,
      profileIcon: `${base}/NavBar/profileIcon.svg`,
      userProfile: `${base}/NavBar/userProfile.svg`,
      logout: `${base}/NavBar/logout.svg`,
      marksAsRead: `${base}/NavBar/markAllAsRead.svg`,
      branding: `${base}/NavBar/branding.jpeg`,
      logo1: `${base}/NavBar/Logo1.png`,
      logo2: `${base}/NavBar/Logo1.svg`,
    },
    Services: {
      mediFacial: `${base}/Services/medi-facial.jpeg`,
      whyUs: `${base}/Services/why-us.jpg`,
      feedback: `${base}/Services/feedback.jpg`,
      lhrPackages: `${base}/Services/LHR-Packages.jpg`,
      lhrPackagesMobile: `${base}/Services/LHR-Packages-Mobile.jpg`,
      mediFacialPackage: `${base}/Services/medi-facial-package-header.jpg`,
      mediFacialPackageMobile: `${base}/Services/medi-facial-package-mobile.jpg`,
      LaserHairRemoval: {
        laserHairSelectedPart: `${base}/Services/LaserHairRemoval/Women/img7.webp`,
        hairRemovalBookNow: `${base}/Services/LaserHairRemoval/HairRemovalBookNow.jpg`,
        laserHairRemovalCard: `${base}/Services/LaserHairRemoval/laser-hair-removal.webp`,
        faceAndNeck: `${base}/Services/LaserHairRemoval/faceAndNeck.jpg`,
        bikiniAndButtocks: `${base}/Services/LaserHairRemoval/bikiniAndButtocks.jpg`,
        underarms: `${base}/Services/LaserHairRemoval/Underarms.webp`,
        fullBodyWomenLHR: `${base}/Services/LaserHairRemoval/fullBodyWomenLHR.jpg`,
        fullBodyMenLHR: `${base}/Services/LaserHairRemoval/fullBodyMenLHR.jpg`,
        chestAndBack: `${base}/Services/LaserHairRemoval/chest-back.webp`,
        home: `${base}/Services/LaserHairRemoval/home.png`,
        machine: `${base}/Services/LaserHairRemoval/machine.webp`,
        back: `${base}/Services/LaserHairRemoval/back.jpg`,
        bikini: `${base}/Services/LaserHairRemoval/bikini.jpg`,
        chest: `${base}/Services/LaserHairRemoval/chest.jpg`,
        facial: `${base}/Services/LaserHairRemoval/facial.jpg`,
        fullLegs: `${base}/Services/LaserHairRemoval/full-legs.jpg`,
        underarmsIcon: `${base}/Services/LaserHairRemoval/underarms.jpg`,
        Men: {
          headerMen: `${base}/Services/LaserHairRemoval/Men/header.jpg`,
          headerMenMobile: `${base}/Services/LaserHairRemoval/Men/headerMobile.jpg`,
          imageOne: `${base}/Services/LaserHairRemoval/Men/img1.webp`,
          imageTwo: `${base}/Services/LaserHairRemoval/Men/img2.webp`,
          imageThree: `${base}/Services/LaserHairRemoval/Men/img3.webp`,
          imageFour: `${base}/Services/LaserHairRemoval/Men/img4.webp`,
          image5: `${base}/Services/LaserHairRemoval/Men/LHR-Men-img2.webp`,
          LHRMenHomeCard: `${base}/Services/LaserHairRemoval/Men/LHRHomeCard.jpg`,
        },
        Women: {
          headerWomen: `${base}/Services/LaserHairRemoval/Women/header.jpg`,
          imageOne: `${base}/Services/LaserHairRemoval/Women/img1.webp`,
          imageTwo: `${base}/Services/LaserHairRemoval/Women/img2.webp`,
          imageThree: `${base}/Services/LaserHairRemoval/Women/img3.webp`,
          imageFour: `${base}/Services/LaserHairRemoval/Women/img4.webp`,
          imageFive: `${base}/Services/LaserHairRemoval/Women/img5.webp`,
          imageSix: `${base}/Services/LaserHairRemoval/Women/img7.webp`,
          imageSeven: `${base}/Services/LaserHairRemoval/Women/img7.webp`,
          LHRWomenHomeCard: `${base}/Services/LaserHairRemoval/Women/LHRWomenHomeCard.png`,
        },
      },
      OxyGeneo: {
        header: `${base}/Services/Oxygeneo/header.jpg`,
        oxygeneoCard: `${base}/Services/Oxygeneo/oxygeneoCard.jpg`,
        img1: `${base}/Services/Oxygeneo/img1.jpg`,
        img2: `${base}/Services/Oxygeneo/img2.jpg`,
        img4: `${base}/Services/Oxygeneo/img4.png`,
        img5: `${base}/Services/Oxygeneo/img5.png`,
        img6: `${base}/Services/Oxygeneo/img6.jpg`,
        img7: `${base}/Services/Oxygeneo/img7.jpg`,
        img8: `${base}/Services/Oxygeneo/img8.jpg`,
        exfoliate: `${base}/Services/Oxygeneo/exfoliate.png`,
        infuse: `${base}/Services/Oxygeneo/infuse.png`,
        oxygenate: `${base}/Services/Oxygeneo/oxygenate.png`,
        oxygenoHomeCard: `${base}/Services/Oxygeneo/oxygenoHomeCard.jpg`,
      },
      OxyHydra: {
        oxyHydraCard: `${base}/Services/OxyHydra/oxyHydra.jpg`,
        header2: `${base}/Services/OxyHydra/header2.jpg`,
        header3: `${base}/Services/OxyHydra/header3.jpg`,
        header: `${base}/Services/OxyHydra/header.jpg`,
        img1: `${base}/Services/OxyHydra/img1.webp`,
        img2: `${base}/Services/OxyHydra/img2.jpg`,
        img3: `${base}/Services/OxyHydra/img3.jpg`,
        img4: `${base}/Services/OxyHydra/img4.jpg`,
        oxyPackage: `${base}/Services/OxyHydra/oxy-package.jpg`,
        oxyHydraHomeCard: `${base}/Services/OxyHydra/oxyHydraHomeCard.jpeg`,
      },
      SkinTightening: {
        skinTighteningCard: `${base}/Services/SkinTightening/skinTighteningCard.jpg`,
        header: `${base}/Services/SkinTightening/header.jpg`,
        img1: `${base}/Services/SkinTightening/img1.jpg`,
        img2: `${base}/Services/SkinTightening/img2.jpg`,
        img3: `${base}/Services/SkinTightening/img3.jpg`,
        img4: `${base}/Services/SkinTightening/img4.png`,
        img5: `${base}/Services/SkinTightening/img5.jpg`,
        img6: `${base}/Services/SkinTightening/img6.jpg`,
        img7: `${base}/Services/SkinTightening/img7.jpg`,
        skinPackage: `${base}/Services/SkinTightening/skin-package.jpg`,
        sTHomeCard: `${base}/Services/SkinTightening/sTHomeCard.webp`,
      },
      Dermafrac: {
        dermafracCard: `${base}/Services/Dermafrac/dermafracCard.jpg`,
        header: `${base}/Services/Dermafrac/header.jpg`,
        imageOne: `${base}/Services/Dermafrac/img1.webp`,
        imageTwo: `${base}/Services/Dermafrac/img2.webp`,
        imageThree: `${base}/Services/Dermafrac/img3.webp`,
        imageFour: `${base}/Services/Dermafrac/img4.webp`,
        image5: `${base}/Services/Dermafrac/img5.webp`,
        img6: `${base}/Services/Dermafrac/img6.jpg`,
        img7: `${base}/Services/Dermafrac/img7.webp`,
        img8: `${base}/Services/Dermafrac/img8.jpg`,
        img9: `${base}/Services/Dermafrac/img9.webp`,
        dermaPackage: `${base}/Services/Dermafrac/derma-package.jpg`,
        dermafracHomeCard: `${base}/Services/Dermafrac/dermafracHomeCard.jpg`,
      },
      BeforeAfter: {
        lhr: {
          img1: `${base}/Services/BeforeAfter/laser-img1.jpg`,
          img2: `${base}/Services/BeforeAfter/laser-img2.jpg`,
          img3: `${base}/Services/BeforeAfter/laser-img3.jpg`,
          img4: `${base}/Services/BeforeAfter/laser-img4.jpg`,
        },
        oxygeneo: {
          img1: `${base}/Services/BeforeAfter/oxygeneo-img1.jpg`,
          img2: `${base}/Services/BeforeAfter/oxygeneo-img2.jpg`,
        },
        oxyhydra: {
          img1: `${base}/Services/BeforeAfter/oxyhydra-img1.jpg`,
          img2: `${base}/Services/BeforeAfter/oxyhydra-img2.jpg`,
        },
        skinTightening: {
          img1: `${base}/Services/BeforeAfter/st-img1.jpg`,
          img2: `${base}/Services/BeforeAfter/st-img2.jpg`,
        },
        dermafrac: {
          img1: `${base}/Services/BeforeAfter/derma-img1.jpg`,
          img2: `${base}/Services/BeforeAfter/derma-img2.jpg`,
        },
      },
    },
    Login: {
      loginBg: `${base}/Login/login-bg.jpg`,
      signupBg: `${base}/Login/signup-bg.jpg`,
      signupBgMobile: `${base}/Login/signupMobile.jpg`,
    },
    ContactUs: {
      contactUs: `${base}/ContactUs/contactUs.jpg`,
    },
    Products: {
      original_img: `${base}/Products/original_img.webp`,
      lowest_price_img: `${base}/Products/lowest_price_img.avif`,
      free_shipping_img: `${base}/Products/free_shipping_img.png`,
      certified: `${base}/Products/certified.png`,
      cod_available: `${base}/Products/cod_available.png`,
      dermat: `${base}/Products/dermat.png`,
      free_delivery: `${base}/Products/free_delivery.png`,
      img1: `${base}/Products/img1.jpg`,
      img2: `${base}/Products/img2.jpg`,
      img3: `${base}/Products/img3.jpg`,
      img4: `${base}/Products/img4.jpg`,
      img5: `${base}/Products/img5.jpg`,
      img6: `${base}/Products/img6.jpg`,
      products: {
        sunscreen: {
          dermaticaAzeProactiveLotion: {
            img1: `${base}/Products/products/sunscreen/dermatica-aze-proactive-lotion/img1.jpeg`,
            img2: `${base}/Products/products/sunscreen/dermatica-aze-proactive-lotion/img2.jpeg`,
            img3: `${base}/Products/products/sunscreen/dermatica-aze-proactive-lotion/img3.jpeg`,
            img4: `${base}/Products/products/sunscreen/dermatica-aze-proactive-lotion/img4.jpeg`,
          },
          berlion: {
            img1: `${base}/Products/products/sunscreen/berlion/img1.webp`,
            img2: `${base}/Products/products/sunscreen/berlion/img2.webp`,
            img3: `${base}/Products/products/sunscreen/berlion/img3.webp`,
            img4: `${base}/Products/products/sunscreen/berlion/img4.webp`,
            img5: `${base}/Products/products/sunscreen/berlion/img5.webp`,
          },
          rayback: {
            img1: `${base}/Products/products/sunscreen/rayback/img1.jpg`,
            img2: `${base}/Products/products/sunscreen/rayback/img2.jpg`,
            img3: `${base}/Products/products/sunscreen/rayback/img3.webp`,
          },
          seeckusSuncreen: {
            img1: `${base}/Products/products/sunscreen/seeckusSuncreen/img1.webp`,
            img2: `${base}/Products/products/sunscreen/seeckusSuncreen/img3.webp`,
            img3: `${base}/Products/products/sunscreen/seeckusSuncreen/img5.webp`,
            img4: `${base}/Products/products/sunscreen/seeckusSuncreen/img6.webp`,
          },
          sunlite: {
            img1: `${base}/Products/products/sunscreen/sunlite/img1.webp`,
            img2: `${base}/Products/products/sunscreen/sunlite/img2.webp`,
            img3: `${base}/Products/products/sunscreen/sunlite/img3.webp`,
            img4: `${base}/Products/products/sunscreen/sunlite/img4.webp`,
          },
          tintSunscreen: {
            img1: `${base}/Products/products/sunscreen/tint-sunscreen/img1.webp`,
            img2: `${base}/Products/products/sunscreen/tint-sunscreen/img2.webp`,
            img3: `${base}/Products/products/sunscreen/tint-sunscreen/img3.webp`,
          },
        },
        faceSerum: {
          ageliteSerum: {
            img1: `${base}/Products/products/face-serum/agelite-serum/img1.jpg`,
          },
          cshine: {
            img1: `${base}/Products/products/face-serum/cshine/img1.jpg`,
            img2: `${base}/Products/products/face-serum/cshine/img2.jpg`,
          },
          ilumeSerum: {
            img1: `${base}/Products/products/face-serum/ilume-serum/img1.jpg`,
          },
        },
        facewash: {
          agelite: {
            img1: `${base}/Products/products/facewash/agelite/img1.jpg`,
            img2: `${base}/Products/products/facewash/agelite/img2.jpg`,
            img3: `${base}/Products/products/facewash/agelite/img3.jpg`,
            img4: `${base}/Products/products/facewash/agelite/img4.jpg`,
          },
          aquaedege: {
            img1: `${base}/Products/products/facewash/aquaedege/img1.jpg`,
            img2: `${base}/Products/products/facewash/aquaedege/img2.jpg`,
            img3: `${base}/Products/products/facewash/aquaedege/img3.jpg`,
          },
          dsglow: {
            img1: `${base}/Products/products/facewash/dsglow/img1.webp`,
            img2: `${base}/Products/products/facewash/dsglow/img5.webp`,
            img3: `${base}/Products/products/facewash/dsglow/img6.webp`,
            img4: `${base}/Products/products/facewash/dsglow/img4.webp`,
          },
          tabulaAst: {
            img1: `${base}/Products/products/facewash/tabula-ast/img1.webp`,
            img2: `${base}/Products/products/facewash/tabula-ast/img2.webp`,
          },
          tabulaOs: {
            img1: `${base}/Products/products/facewash/tabula-os/img1.webp`,
            img2: `${base}/Products/products/facewash/tabula-os/img2.webp`,
          },
          tabulaRasaDs: {
            img1: `${base}/Products/products/facewash/tabula-rasa-ds/img1.webp`,
            img2: `${base}/Products/products/facewash/tabula-rasa-ds/img2.png`,
          },
        },
        moisturiser: {
          cerasoft: {
            img1: `${base}/Products/products/moisturiser/cerasoft/img1.jpg`,
            img2: `${base}/Products/products/moisturiser/cerasoft/img2.jpg`,
          },
          fiMoist: {
            img1: `${base}/Products/products/moisturiser/fi-moist/img1.jpg`,
          },
          moiser: {
            img1: `${base}/Products/products/moisturiser/moiser/img1.jpg`,
          },
          relizmaLotion: {
            img1: `${base}/Products/products/moisturiser/relizma-lotion/img1.webp`,
            img2: `${base}/Products/products/moisturiser/relizma-lotion/img2.webp`,
          },
          uligo: {
            img1: `${base}/Products/products/moisturiser/uligo/img1.jpg`,
            img2: `${base}/Products/products/moisturiser/uligo/img2.jpg`,
          },
          uresoft: {
            img1: `${base}/Products/products/moisturiser/uresoft/img1.webp`,
            img2: `${base}/Products/products/moisturiser/uresoft/img2.webp`,
            img3: `${base}/Products/products/moisturiser/uresoft/img3.webp`,
          },
        },
        pigmentation: {
          glambakUltra: {
            img1: `${base}/Products/products/pigmentation/glambak-ultra/img1.webp`,
          },
          kcliteGold: {
            img1: `${base}/Products/products/pigmentation/kclite-gold/img1.jpg`,
          },
          lumiedgeCream: {
            img1: `${base}/Products/products/pigmentation/lumiedge-cream/img1.jpg`,
            img2: `${base}/Products/products/pigmentation/lumiedge-cream/img2.jpg`,
            img3: `${base}/Products/products/pigmentation/lumiedge-cream/img3.jpg`,
            img4: `${base}/Products/products/pigmentation/lumiedge-cream/img4.jpg`,
          },
          lumiedgeTx: {
            img1: `${base}/Products/products/pigmentation/lumiedge-tx/img1.jpg`,
          },
          melaluminUltra: {
            img1: `${base}/Products/products/pigmentation/melalumin-ultra/img1.webp`,
            img2: `${base}/Products/products/pigmentation/melalumin-ultra/img2.webp`,
            img3: `${base}/Products/products/pigmentation/melalumin-ultra/img3.webp`,
          },
          transglowHd: {
            img1: `${base}/Products/products/pigmentation/transglow-hd/img1.webp`,
            img2: `${base}/Products/products/pigmentation/transglow-hd/img2.webp`,
          },
        },
        skinAntioxidant: {
          cwiz: {
            img1: `${base}/Products/products/skin-antioxient/cwiz/img1.jpg`,
          },
          glutasurgeA: {
            img1: `${base}/Products/products/skin-antioxient/flutasurge-a/img1.webp`,
            img2: `${base}/Products/products/skin-antioxient/flutasurge-a/img2.png`,
          },
          glFizz: {
            img1: `${base}/Products/products/skin-antioxient/gl-fizz/img1.jpg`,
          },
          glootamin: {
            img1: `${base}/Products/products/skin-antioxient/glootamin/img1.webp`,
            img2: `${base}/Products/products/skin-antioxient/glootamin/img2.webp`,
          },
          glutasurgeC: {
            img1: `${base}/Products/products/skin-antioxient/glutasurge-c/img1.jpg`,
          },
        },
      },
    },
  },
};

export default Resources;
