export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const ADD_TO_SERVICE_CART = "ADD_TO_SERVICE_CART";
export const REMOVE_FROM_SERVICE_CART = "REMOVE_FROM_SERVICE_CART";
export const EMPTY_SERVICE_CART = "EMPTY_SERVICE_CART";
