export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
